In [19]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score

import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense,Input

In [6]:
df = pd.read_csv('Admission_Predict_Ver1.1.csv')

In [7]:
df.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65

In [9]:
df.shape

(500, 9)

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Serial No.         500 non-null    int64
 1   GRE Score          500 non-null    int64
 2   TOEFL Score        500 non-null    int64
 3   University Rating  500 non-null    int64
 4   SOP                500 non-null    float64
 5   LOR                500 non-null    float64
 6   CGPA               500 non-null    float64
 7   Research           500 non-null    int64
 8   Chance of Admit    500 non-null    float64
dtypes: float64(4), int64(5)
memory usage: 35.3 KB

In [ ]:
# Observations :
#   Serial No is obviously just the index so we will just remove it 
#   GRE Scale is large in scale and we have to normalize them so that our ann model can learn the parameters easily.
#       So we will use here MinMixScaler instead because there is a tight upper and lower bound here .

In [12]:
df = df.drop(columns=['Serial No.'])

In [13]:
df.head()

,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,337,118,4,4.5,4.5,9.65,1,0.92
1,324,107,4,4.0,4.5,8.87,1,0.76
2,316,104,3,3.0,3.5,8.00,1,0.72
3,322,110,3,3.5,2.5,8.67,1,0.80
4,314,103,2,2.0,3.0,8.21,0,0.65

In [17]:
# Split the dataset into two

In [14]:
X,y = df.iloc[:,0:-1],df.iloc[:,-1]

In [29]:
X.shape,y.shape

((500, 7), (500,))

In [15]:
X.head()

   GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research
0        337          118                  4  4.5   4.5  9.65         1
1        324          107                  4  4.0   4.5  8.87         1
2        316          104                  3  3.0   3.5  8.00         1
3        322          110                  3  3.5   2.5  8.67         1
4        314          103                  2  2.0   3.0  8.21         0

In [16]:
y.head()

0    0.92
1    0.76
2    0.72
3    0.80
4    0.65
Name: Chance of Admit , dtype: float64

In [20]:
# Then split into training and testing set with appropriate proportions
X_train ,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [21]:
# Now scale these value using  MinMaxScaler

In [22]:
scaler = MinMaxScaler()

# Always fit on training set beforehand and then only apply transform to both especially test set to avoid data leaks
scaler.fit(X_train)

X_train_scalled = scaler.transform(X_train)
X_test_scalled = scaler.transform(X_test)

In [26]:
X_train_scalled[:5] # Skim the top5 values

array([[0.62      , 0.67857143, 0.5       , 0.625     , 0.71428571,
        0.65064103, 1.        ],
       [0.52      , 0.67857143, 0.75      , 0.75      , 1.        ,
        0.55769231, 0.        ],
       [0.26      , 0.35714286, 0.5       , 0.625     , 0.42857143,
        0.54487179, 0.        ],
       [0.48      , 0.53571429, 0.25      , 0.375     , 0.71428571,
        0.47115385, 0.        ],
       [0.36      , 0.5       , 0.5       , 0.625     , 0.28571429,
        0.45192308, 1.        ]])

In [27]:
X_test_scalled[:5] # Skim the top5 values

array([[0.88      , 0.85714286, 0.75      , 0.75      , 0.57142857,
        0.87820513, 1.        ],
       [0.48      , 0.57142857, 0.75      , 0.875     , 0.71428571,
        0.71794872, 1.        ],
       [0.5       , 0.46428571, 0.25      , 0.25      , 0.28571429,
        0.2724359 , 0.        ],
       [0.44      , 0.60714286, 0.5       , 0.5       , 0.42857143,
        0.60576923, 0.        ],
       [0.72      , 0.71428571, 0.5       , 0.625     , 0.42857143,
        0.72115385, 1.        ]])

In [31]:
# Build the model
model = Sequential()
model.add(Input(shape=(X_train_scalled.shape[0],)))
model.add(Dense(7,activation='relu'))
model.add(Dense(1,activation='linear'))

In [32]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 7)              │         2,807 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             8 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,815 (11.00 KB)

 Trainable params: 2,815 (11.00 KB)

 Non-trainable params: 0 (0.00 B)